version: '3.7'

networks:
  universidades.com:
    external: true

services:
  explorerdb.universidades.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.universidades.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    volumes:
      - ./explorerdb:/var/lib/postgresql/data
    networks:
      - universidades.com

  explorer.universidades.com:
    image: hyperledger/explorer:latest
    container_name: explorer.universidades.com
    environment:
      - DATABASE_HOST=explorerdb.universidades.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./crypto-config:/opt/explorer/app/platform/fabric/crypto-config
    ports:
      - "8080:8080"
    depends_on:
      - explorerdb.universidades.com
    networks:
      - universidades.com
